// Generated from src/assets by scripts/generate-asset-types.js. Do not edit by hand.

export type AttackType = 'BlackZone' | 'RedZone' | 'Weapon';

export type CarryState =
  | 'BodyCarry_DBNO_Carrier'
  | 'BodyCarry_End_Carried'
  | 'BodyCarry_End_Carrier'
  | 'BodyCarry_Start_Carried'
  | 'BodyCarry_Start_Carrier';

export type DamageReason =
  | 'ArmShot'
  | 'HeadShot'
  | 'LegShot'
  | 'None'
  | 'NonSpecific'
  | 'PelvisShot'
  | 'SimlateAIBeKilled'
  | 'SimulateAIBeKilled'
  | 'TorsoShot';

export type ObjectTypeStatus =
  | 'ACTIVATED'
  | 'Closing'
  | 'false'
  | 'FuelSpill'
  | 'Ignite'
  | 'Opening'
  | 'Play'
  | 'Stop'
  | 'true'
  | 'Ascender_End_Dismount_Bottom'
  | 'Ascender_End_Dismount_Top'
  | 'Ascender_Start_Mount_Bottom'
  | 'Ascender_Start_Mount_Top'
  | 'LockedDoor_Unlocked';

export type ObjectType =
  | 'Caraudio'
  | 'Door'
  | 'DoubleSlidingDoor'
  | 'Fence'
  | 'FuelPuddle'
  | 'Hay'
  | 'Jerrycan'
  | 'JerryCan'
  | 'Jukebox'
  | 'JukeBox'
  | 'PropaneTank'
  | 'VendingMachine'
  | 'Window'
  | 'Ascender'
  | 'GasPump'
  | 'LockedDoor'
  | 'BulletproofShield'
  | 'Cartoplights';

export type RegionIdChimera_Main = 'Lab' | 'Level_A' | 'Level_B' | 'Level_C' | 'Level_D' | 'Ruins';

export type RegionIdDesert_Main =
  | 'alcantara'
  | 'ruins'
  | 'lacobreria'
  | 'trailerpark'
  | 'craterfields'
  | 'elpozo'
  | 'watertreatment'
  | 'sanmartin'
  | 'heciendadelpatron'
  | 'powergrid'
  | 'cruzdelvalle'
  | 'torreahumada'
  | 'campomilitar'
  | 'tierrabronca'
  | 'elazahar'
  | 'junkyard'
  | 'minasgenerales'
  | 'graveyard'
  | 'montenuevo'
  | 'ladrillera'
  | 'chumacera'
  | 'pecado'
  | 'labendita'
  | 'lmpala'
  | 'losleones'
  | 'puertoparaiso'
  | 'loshigos'
  | 'prison'
  | 'minasdelsur'
  | 'valledelmar';

export type RegionIdDihorOtok_Main =
  | 'port'
  | 'cosmodrome'
  | 'trevno'
  | 'peshkova'
  | 'mountkreznic'
  | 'goroka'
  | 'dobromesto'
  | 'vihar'
  | 'movatra'
  | 'dinopark'
  | 'tovar'
  | 'castle'
  | 'podvosto'
  | 'cementfactory'
  | 'cantra'
  | 'hotspring'
  | 'volnova'
  | 'abbey'
  | 'winery'
  | 'milnar'
  | 'zabava'
  | 'krichas'
  | 'coalmine'
  | 'lumberyard'
  | 'pilnec'
  | 'sawmill';

export type RegionIdErangel_Main =
  | 'zharki'
  | 'shootingrange'
  | 'severny'
  | 'stalber'
  | 'kameshki'
  | 'yasnayapolyana'
  | 'lipovka'
  | 'mansion'
  | 'shelter'
  | 'prison'
  | 'myltapower'
  | 'mylta'
  | 'farm'
  | 'rozhok'
  | 'school'
  | 'georgopol'
  | 'hospital'
  | 'gatka'
  | 'quarry'
  | 'primorsk'
  | 'ferrypier'
  | 'sosnovkamilitarybase'
  | 'novorepnoye'
  | 'ruins'
  | 'pochinki';

export type RegionIdHeaven_Main =
  | 'coalyards'
  | 'docks'
  | 'industrialpark'
  | 'railyard'
  | 'residential'
  | 'steelmill';

export type RegionIdSavage_Main =
  | 'kampong'
  | 'getaway'
  | 'lawaki'
  | 'campbravo'
  | 'airfield'
  | 'khao'
  | 'tatmok'
  | 'paradiseresort'
  | 'bootcamp'
  | 'quarry'
  | 'cave'
  | 'campalpha'
  | 'campcharlie'
  | 'bantai'
  | 'painan'
  | 'sahmee'
  | 'nakham'
  | 'tambang'
  | 'ruins'
  | 'hatinh';

export type RegionIdSummerland_Main =
  | 'alhabar'
  | 'alhayik'
  | 'bahrsahir'
  | 'bashara'
  | 'cargoship'
  | 'hadiqanemo';

export type RegionIdTiger_Main =
  | 'airport'
  | 'armybase'
  | 'buksansa'
  | 'fishingcamp'
  | 'godok'
  | 'haemoosa'
  | 'hapo'
  | 'hosan'
  | 'hosanprison'
  | 'kangneung'
  | 'ohyang'
  | 'palace'
  | 'school'
  | 'shipyard'
  | 'songam'
  | 'studio'
  | 'terminal'
  | 'wolsong'
  | 'yongcheon';

export type WeatherId =
  | 'Clear'
  | 'Clear_02'
  | 'Clouds'
  | 'Cloudy'
  | 'Christmas'
  | 'Dark'
  | 'Halloween'
  | 'Night'
  | 'Overcast'
  | 'Snow'
  | 'Sunrise'
  | 'Sunset'
  | 'Sunset_a'
  | 'Weather_Clear'
  | 'Weather_Overcast'
  | 'Weather_Range_Sunset'
  | 'Weather_Sunset'
  | 'Weather_Summerland_01';
