// Generated from PUBG API assets
// Last updated: 2025-07-28T14:39:41.302Z

export interface VehicleDictionary {
  [key: string]: string;
}

export const VEHICLE_DICTIONARY: VehicleDictionary = {
  "AirBoat_V2_C": "Airboat",
  "AquaRail_A_01_C": "Aquarail",
  "AquaRail_A_02_C": "Aquarail",
  "AquaRail_A_03_C": "Aquarail",
  "AquaRail_C": "AquaRail",
  "BP_ATV_C": "Quad",
  "BP_BRDM_C": "BRDM-2",
  "BP_Bicycle_C": "Mountain Bike",
  "BP_Blanc_C": "Coupe SUV",
  "BP_CoupeRB_C": "Coupe RB",
  "BP_DO_Circle_Train_Merged_C": "Train",
  "BP_DO_Line_Train_Dino_Merged_C": "Train",
  "BP_DO_Line_Train_Merged_C": "Train",
  "BP_Dirtbike_C": "Dirt Bike",
  "BP_EmergencyPickupVehicle_C": "Emergency Pickup",
  "BP_Food_Truck_C": "Food Truck",
  "BP_KillTruck_C": "Kill Truck",
  "BP_LootTruck_C": "Loot Truck",
  "BP_M_Rony_A_01_C": "Rony",
  "BP_M_Rony_A_02_C": "Rony",
  "BP_M_Rony_A_03_C": "Rony",
  "BP_McLarenGT_Lx_Yellow_C": "McLaren GT (Elite Yellow)",
  "BP_McLarenGT_St_white_C": "McLaren GT (Standard White)",
  "BP_McLarenGT_St_black_C": "McLaren GT (Standard Black)",
  "BP_Mirado_A_02_C": "Mirado",
  "BP_Mirado_A_03_C": "Mirado",
  "BP_Mirado_A_03_Esports_C": "Mirado",
  "BP_Mirado_Open_03_C": "Mirado (open top)",
  "BP_Mirado_Open_04_C": "Mirado (open top)",
  "BP_Mirado_Open_05_C": "Mirado (open top)",
  "BP_Motorbike_04_C": "Motorcycle",
  "BP_Motorbike_04_Desert_C": "Motorcycle",
  "BP_Motorbike_04_SideCar_C": "Motorcycle (w/ Sidecar)",
  "BP_Motorbike_04_SideCar_Desert_C": "Motorcycle (w/ Sidecar)",
  "BP_Motorbike_Solitario_C": "Motorcycle",
  "BP_Motorglider_C": "Motor Glider",
  "BP_Motorglider_Green_C": "Motor Glider",
  "BP_Niva_01_C": "Zima",
  "BP_Niva_02_C": "Zima",
  "BP_Niva_03_C": "Zima",
  "BP_Niva_04_C": "Zima",
  "BP_Niva_05_C": "Zima",
  "BP_Niva_06_C": "Zima",
  "BP_Niva_07_C": "Zima",
  "BP_Niva_Esports_C": "Zima",
  "BP_PickupTruck_A_01_C": "Pickup Truck (closed top)",
  "BP_PickupTruck_A_02_C": "Pickup Truck (closed top)",
  "BP_PickupTruck_A_03_C": "Pickup Truck (closed top)",
  "BP_PickupTruck_A_04_C": "Pickup Truck (closed top)",
  "BP_PickupTruck_A_05_C": "Pickup Truck (closed top)",
  "BP_PickupTruck_A_esports_C": "Pickup Truck (closed top)",
  "BP_PickupTruck_B_01_C": "Pickup Truck (open top)",
  "BP_PickupTruck_B_02_C": "Pickup Truck (open top)",
  "BP_PickupTruck_B_03_C": "Pickup Truck (open top)",
  "BP_PickupTruck_B_04_C": "Pickup Truck (open top)",
  "BP_PickupTruck_B_05_C": "Pickup Truck (open top)",
  "BP_Pillar_Car_C": "Pillar Security Car",
  "BP_PonyCoupe_C": "Pony Coupe",
  "BP_Porter_C": "Porter",
  "BP_Scooter_01_A_C": "Scooter",
  "BP_Scooter_02_A_C": "Scooter",
  "BP_Scooter_03_A_C": "Scooter",
  "BP_Scooter_04_A_C": "Scooter",
  "BP_Snowbike_01_C": "Snowbike",
  "BP_Snowbike_02_C": "Snowbike",
  "BP_Snowmobile_01_C": "Snowmobile",
  "BP_Snowmobile_02_C": "Snowmobile",
  "BP_Snowmobile_03_C": "Snowmobile",
  "BP_Special_FbrBike_C": "Special FBR Bike",
  "BP_TukTukTuk_A_01_C": "Tukshai",
  "BP_TukTukTuk_A_02_C": "Tukshai",
  "BP_TukTukTuk_A_03_C": "Tukshai",
  "BP_Van_A_01_C": "Van",
  "BP_Van_A_02_C": "Van",
  "BP_Van_A_03_C": "Van",
  "Boat_PG117_C": "PG-117",
  "Buggy_A_01_C": "Buggy",
  "Buggy_A_02_C": "Buggy",
  "Buggy_A_03_C": "Buggy",
  "Buggy_A_04_C": "Buggy",
  "Buggy_A_05_C": "Buggy",
  "Buggy_A_06_C": "Buggy",
  "Dacia_A_01_v2_C": "Dacia 1300",
  "Dacia_A_01_v2_snow_C": "Dacia 1300",
  "Dacia_A_02_v2_C": "Dacia 1300",
  "Dacia_A_03_v2_C": "Dacia 1300",
  "Dacia_A_03_v2_Esports_C": "Dacia 1300",
  "Dacia_A_04_v2_C": "Dacia 1300",
  "DummyTransportAircraft_C": "C-130",
  "EmergencyAircraft_Tiger_C": "Emergency Aircraft",
  "MortarPawn_C": "Mortar",
  "PG117_A_01_C": "PG-117",
  "ParachutePlayer_C": "Parachute",
  "ParachutePlayer_Warmode_C": "Parachute",
  "RedeployAircraft_DihorOtok_C": "Helicopter",
  "RedeployAircraft_Tiger_C": "Helicopter",
  "TransportAircraft_Chimera_C": "Helicopter",
  "TransportAircraft_Tiger_C": "Helicopter",
  "Uaz_A_01_C": "UAZ (open top)",
  "Uaz_Armored_C": "UAZ (armored)",
  "Uaz_B_01_C": "UAZ (soft top)",
  "Uaz_B_01_esports_C": "UAZ (soft top)",
  "Uaz_C_01_C": "UAZ (hard top)",
  "WarModeTransportAircraft_C": "C-130"
};

export type VehicleId = 'AirBoat_V2_C' | 'AquaRail_A_01_C' | 'AquaRail_A_02_C' | 'AquaRail_A_03_C' | 'AquaRail_C' | 'BP_ATV_C' | 'BP_BRDM_C' | 'BP_Bicycle_C' | 'BP_Blanc_C' | 'BP_CoupeRB_C' | 'BP_DO_Circle_Train_Merged_C' | 'BP_DO_Line_Train_Dino_Merged_C' | 'BP_DO_Line_Train_Merged_C' | 'BP_Dirtbike_C' | 'BP_EmergencyPickupVehicle_C' | 'BP_Food_Truck_C' | 'BP_KillTruck_C' | 'BP_LootTruck_C' | 'BP_M_Rony_A_01_C' | 'BP_M_Rony_A_02_C' | 'BP_M_Rony_A_03_C' | 'BP_McLarenGT_Lx_Yellow_C' | 'BP_McLarenGT_St_white_C' | 'BP_McLarenGT_St_black_C' | 'BP_Mirado_A_02_C' | 'BP_Mirado_A_03_C' | 'BP_Mirado_A_03_Esports_C' | 'BP_Mirado_Open_03_C' | 'BP_Mirado_Open_04_C' | 'BP_Mirado_Open_05_C' | 'BP_Motorbike_04_C' | 'BP_Motorbike_04_Desert_C' | 'BP_Motorbike_04_SideCar_C' | 'BP_Motorbike_04_SideCar_Desert_C' | 'BP_Motorbike_Solitario_C' | 'BP_Motorglider_C' | 'BP_Motorglider_Green_C' | 'BP_Niva_01_C' | 'BP_Niva_02_C' | 'BP_Niva_03_C' | 'BP_Niva_04_C' | 'BP_Niva_05_C' | 'BP_Niva_06_C' | 'BP_Niva_07_C' | 'BP_Niva_Esports_C' | 'BP_PickupTruck_A_01_C' | 'BP_PickupTruck_A_02_C' | 'BP_PickupTruck_A_03_C' | 'BP_PickupTruck_A_04_C' | 'BP_PickupTruck_A_05_C' | 'BP_PickupTruck_A_esports_C' | 'BP_PickupTruck_B_01_C' | 'BP_PickupTruck_B_02_C' | 'BP_PickupTruck_B_03_C' | 'BP_PickupTruck_B_04_C' | 'BP_PickupTruck_B_05_C' | 'BP_Pillar_Car_C' | 'BP_PonyCoupe_C' | 'BP_Porter_C' | 'BP_Scooter_01_A_C' | 'BP_Scooter_02_A_C' | 'BP_Scooter_03_A_C' | 'BP_Scooter_04_A_C' | 'BP_Snowbike_01_C' | 'BP_Snowbike_02_C' | 'BP_Snowmobile_01_C' | 'BP_Snowmobile_02_C' | 'BP_Snowmobile_03_C' | 'BP_Special_FbrBike_C' | 'BP_TukTukTuk_A_01_C' | 'BP_TukTukTuk_A_02_C' | 'BP_TukTukTuk_A_03_C' | 'BP_Van_A_01_C' | 'BP_Van_A_02_C' | 'BP_Van_A_03_C' | 'Boat_PG117_C' | 'Buggy_A_01_C' | 'Buggy_A_02_C' | 'Buggy_A_03_C' | 'Buggy_A_04_C' | 'Buggy_A_05_C' | 'Buggy_A_06_C' | 'Dacia_A_01_v2_C' | 'Dacia_A_01_v2_snow_C' | 'Dacia_A_02_v2_C' | 'Dacia_A_03_v2_C' | 'Dacia_A_03_v2_Esports_C' | 'Dacia_A_04_v2_C' | 'DummyTransportAircraft_C' | 'EmergencyAircraft_Tiger_C' | 'MortarPawn_C' | 'PG117_A_01_C' | 'ParachutePlayer_C' | 'ParachutePlayer_Warmode_C' | 'RedeployAircraft_DihorOtok_C' | 'RedeployAircraft_Tiger_C' | 'TransportAircraft_Chimera_C' | 'TransportAircraft_Tiger_C' | 'Uaz_A_01_C' | 'Uaz_Armored_C' | 'Uaz_B_01_C' | 'Uaz_B_01_esports_C' | 'Uaz_C_01_C' | 'WarModeTransportAircraft_C';

